server:
  port: 8080
  mode: debug

database:
  driver: mysql
  host: "172.25.13.23"
  port: 3306
  username: "root"
  password: "123"
  dbname: "zg_shop"
  charset: "utf8mb4"

redis:
  host: "172.25.13.23"
  port: 6379
  password: "123"
  db: 0 

email:
  host: "127.0.0.1"
  port: 587
  username: "2897046312@qq.com"
  password: "—"
  from: "2897046312@qq.com"

# 添加支付配置
payment:
  wechat:
    app_id: "your_wechat_appid"
    mch_id: "your_wechat_mchid"
    api_key: "your_wechat_apikey"
    notify_url: "http://your.domain/api/v1/payments/wechat/callback"
  
  alipay:
    app_id: "your_alipay_appid"
    private_key: "your_alipay_privatekey"
    public_key: "your_alipay_publickey"
    notify_url: "http://your.domain/api/v1/payments/alipay/callback"

  paypal: 
    paypal_client_id: "Aa-gSJ9un3HBdjCxdkxlEiDo4UAvypyTHmGsFBSo1x2G34zL4B1QHfvLqPmEXlUitXZYbFj8APJ0Furj"
    paypal_secret: "EIX90rm7Ll_l61HHY51ncgvqRWKJ80Qp1Ex4BNIHUFAK0d7HE9PUpjxdrH_lQWNJfLcQ0aeiRTnZ3dkC"
    paypal_api_base: "https://api.sandbox.paypal.com"